[package]
name = "zk-snark-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bellman = "0.14.0"
rand = "0.8"
ff = "0.8"
bls12_381 = "0.4"